import {ELEMENTS,SHIPS,WEAPONS,ENGINES,MODULES,findById} from './data.js';
import {AudioSystem} from './audio.js';
import {AtomGame} from './game.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DEFAULT_SAVE={version:1,unlocked:1,completed:{},best:{},electrons:0,neutrons:0,purchased:{ships:['pico'],weapons:['blaster2'],engines:['project1'],modules:[]},selectedShip:'pico',selectedWeapon:'blaster2',selectedEngine:'project1',selectedModules:[],tutorialDone:false,settings:{sfx:true,music:false,side:'right',stick:'medium',deadzone:.38}};
function loadSave(){try{const x=JSON.parse(localStorage.getItem('atom-shooter-save')||'null');return x?mergeSave(x):structuredClone(DEFAULT_SAVE)}catch{return structuredClone(DEFAULT_SAVE)}}
function mergeSave(x){return{...structuredClone(DEFAULT_SAVE),...x,purchased:{...DEFAULT_SAVE.purchased,...(x.purchased||{})},settings:{...DEFAULT_SAVE.settings,...(x.settings||{})},completed:x.completed||{},best:x.best||{},selectedModules:x.selectedModules||[]}}
let save=loadSave(),currentScreen='main',shopTab='ships',gameContext=null,toastTimer=null;
const audio=new AudioSystem(); audio.configure(save.settings);
const game=new AtomGame($('#game-canvas'),audio,{onHUD:updateHUD,onObjective:t=>$('#objective').textContent=t,onCurrency:()=>{persist();updateWallets()},onPause:showPause,onComplete:levelComplete,onGameOver:gameOver,onLifeLost:()=>updateHUD()});
function persist(){localStorage.setItem('atom-shooter-save',JSON.stringify(save))}
function showScreen(name){currentScreen=name;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));if(name==='main')updateMain();if(name==='table')renderTable();if(name==='shop')renderShop();if(name==='options')syncSettings();updateWallets()}
function updateMain(){const n=save.unlocked;$('#continue-hint').textContent=n>1?`${n-1} / 118 elements cleared • ${ELEMENTS[Math.min(n-1,117)].name} available`:''}
function updateWallets(){for(const id of ['table-electrons','shop-electrons','game-electrons']){const el=$('#'+id);if(el)el.textContent=save.electrons}for(const id of ['table-neutrons','shop-neutrons','game-neutrons']){const el=$('#'+id);if(el)el.textContent=save.neutrons}}
function renderTable(){const root=$('#periodic-table');root.innerHTML='';for(const e of ELEMENTS){const b=document.createElement('button');const done=!!save.completed[e.z],open=e.z<=save.unlocked;b.className=`element-cell ${done?'completed':open?'available':'locked'} ${e.z===save.unlocked?'current':''}`;b.style.gridColumn=e.col;b.style.gridRow=e.row;b.disabled=!open;b.innerHTML=`<span class="z">${e.z}</span><b class="sym">${e.symbol}</b><span class="nm">${e.name}</span>`;b.title=open?`${e.z}. ${e.name}${done?` — ${save.completed[e.z]}★`:''}`:'Complete the previous element to unlock';if(open)b.addEventListener('click',()=>startGame(e.z-1,'classic'));root.appendChild(b)}}
function renderShop(){const tabs=$$('#shop-tabs button');tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===shopTab));const map={ships:SHIPS,weapons:WEAPONS,engines:ENGINES,modules:MODULES},list=map[shopTab],root=$('#shop-grid');root.innerHTML='';for(const item of list){const owned=save.purchased[shopTab].includes(item.id),selected=isSelected(shopTab,item.id),can=save.electrons>=item.costE&&save.neutrons>=item.costN;const card=document.createElement('article');card.className=`item-card ${selected?'selected':''}`;let stats='';if(shopTab==='ships')stats=`<span class="chip">Mass ${item.mass.toFixed(2)}</span><span class="chip">Slots ${item.slots}</span>`;if(shopTab==='weapons')stats=`<span class="chip">${item.bullets} projectile${item.bullets>1?'s':''}</span><span class="chip">${item.rate.toFixed(1)}/s</span>`;if(shopTab==='engines')stats=`<span class="chip">Thrust ×${item.thrust}</span>`;if(shopTab==='modules')stats=`<span class="chip">Passive module</span>`;const label=owned?(selected?'Equipped':(shopTab==='modules'?'Equip module':'Equip')):'Buy';card.innerHTML=`<h3>${item.name}</h3><p>${item.desc}</p><div class="stats">${stats}</div><div class="price"><span><i class="e-dot"></i>${item.costE}</span><span><i class="n-dot"></i>${item.costN}</span></div><button class="${!owned?'primary':''}" ${!owned&&!can?'disabled':''}>${label}</button>`;card.querySelector('button').addEventListener('click',()=>buyOrEquip(shopTab,item));root.appendChild(card)}renderLoadout()}
function isSelected(tab,id){if(tab==='ships')return save.selectedShip===id;if(tab==='weapons')return save.selectedWeapon===id;if(tab==='engines')return save.selectedEngine===id;return save.selectedModules.includes(id)}
function buyOrEquip(tab,item){const owned=save.purchased[tab].includes(item.id);if(!owned){if(save.electrons<item.costE||save.neutrons<item.costN)return;save.electrons-=item.costE;save.neutrons-=item.costN;save.purchased[tab].push(item.id);toast(`${item.name} purchased`)}if(tab==='ships')save.selectedShip=item.id;else if(tab==='weapons')save.selectedWeapon=item.id;else if(tab==='engines')save.selectedEngine=item.id;else{const ship=findById(SHIPS,save.selectedShip),idx=save.selectedModules.indexOf(item.id);if(idx>=0)save.selectedModules.splice(idx,1);else if(save.selectedModules.length<ship.slots)save.selectedModules.push(item.id);else{toast(`This ship has ${ship.slots} module slot${ship.slots===1?'':'s'}`);persist();renderShop();return}}persist();renderShop();updateWallets()}
function renderLoadout(){const ship=findById(SHIPS,save.selectedShip),weapon=findById(WEAPONS,save.selectedWeapon),engine=findById(ENGINES,save.selectedEngine),mods=save.selectedModules.map(id=>findById(MODULES,id).name);$('#loadout-panel').innerHTML=`<b>${ship.name}</b><div class="slots"><span class="slot">⚡ ${engine.name}</span><span class="slot">◉ ${weapon.name}</span>${mods.map(m=>`<span class="slot">◇ ${m}</span>`).join('')}${Array.from({length:Math.max(0,ship.slots-mods.length)},()=>'<span class="slot">+ Empty slot</span>').join('')}</div>`}
function startGame(index,mode,tutorial=false,marathonScore=0){audio.unlock();gameContext={index,mode,tutorial,marathonScore};showScreen('game');applyControlSettings();$('#tutorial-callout').classList.add('hidden');game.start({elementIndex:index,mode,save,tutorial,marathonScore});$('#objective').textContent=tutorial?'Shoot the orbiting electron.':'Shoot and collect the electrons';if(tutorial)runTutorial()}
function updateHUD(h){if(!h)return;$('#element-symbol').textContent=h.element.symbol;$('#element-name').textContent=h.element.name;$('#score').textContent=h.score.toLocaleString();$('#life-indicator').innerHTML=Array.from({length:3},(_,i)=>`<span class="life-ship ${i>=h.lives?'lost':''}">▲</span>`).join('');if(h.phase==='electrons')$('#objective').textContent=`Shoot electrons • ${h.orbiting} remaining`;if(h.phase==='post')$('#objective').textContent=`Neutrons ${h.neutronCollected}/${h.neutronGoal} • avoid red protons`;updateWallets()}
function levelComplete(result){save.completed[result.element.z]=Math.max(save.completed[result.element.z]||0,result.stars);save.best[result.element.z]=Math.max(save.best[result.element.z]||0,result.levelScore);if(result.mode==='classic')save.unlocked=Math.max(save.unlocked,Math.min(118,result.element.z+1));if(result.mode==='tutorial')save.tutorialDone=true;persist();const next=result.element.z<118?result.element.z:null;showModal('Level Completed!',`<p><b>${result.element.name}</b> destabilized.</p><p>${'★'.repeat(result.stars)}${'☆'.repeat(3-result.stars)} &nbsp; ${formatTime(result.time)} &nbsp; Score ${result.levelScore.toLocaleString()}</p>`,[
 {label:'Main menu',fn:()=>{closeModal();showScreen('main')}},
 ...(result.mode==='classic'&&next!==null?[{label:'Next element',primary:true,fn:()=>{closeModal();startGame(next,'classic')}}]:[]),
 ...(result.mode==='marathon'&&next!==null?[{label:'Continue',primary:true,fn:()=>{closeModal();startGame(next,'marathon',false,result.score)}}]:[]),
 ...(result.mode==='tutorial'?[{label:'Classic mode',primary:true,fn:()=>{closeModal();showScreen('table')}}]:[])
 ])}
function gameOver(r){showModal('Game Over!',`<p>${r.element.name} won this round.</p><p>Score: <b>${r.score.toLocaleString()}</b></p>`,[{label:'Main menu',fn:()=>{closeModal();showScreen('main')}},{label:'Restart',primary:true,fn:()=>{closeModal();startGame(gameContext.index,gameContext.mode,gameContext.tutorial,gameContext.mode==='marathon'?0:gameContext.marathonScore)}}])}
function showPause(){if(!game.running)return;game.setPaused(true);showModal('Game Paused',`<p>${game.element.name} • Score ${game.score.toLocaleString()}</p>`,[{label:'Quit',fn:()=>{game.stop();closeModal();showScreen(game.mode==='classic'?'table':'main')}},{label:'Restart',fn:()=>{closeModal();startGame(gameContext.index,gameContext.mode,gameContext.tutorial,gameContext.marathonScore)}},{label:'Resume',primary:true,fn:()=>{closeModal();game.setPaused(false)}}],false)}
function runTutorial(){const box=$('#tutorial-callout');box.classList.remove('hidden');const steps=['Welcome to Atom Shooter!','This is your ship. Use WASD / arrows, or the analog stick, to aim.','Push the stick farther to engage thrust. Inertia keeps you moving.','Tap FIRE or press Space to shoot the orbiting electron.','Collect the cyan electron after shooting it down.','When the nucleus explodes, collect blue neutrons and avoid red protons.'];let i=0;box.textContent=steps[0];const timer=setInterval(()=>{if(currentScreen!=='game'||!game.tutorial||!game.running){clearInterval(timer);return}i++;if(i>=steps.length){box.classList.add('hidden');clearInterval(timer)}else box.textContent=steps[i]},4300)}
function showModal(title,body,actions,allowBackdrop=true){const m=$('#modal');$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;const a=$('#modal-actions');a.innerHTML='';for(const x of actions){const b=document.createElement('button');b.textContent=x.label;if(x.primary)b.classList.add('primary');b.addEventListener('click',x.fn);a.appendChild(b)}m.classList.remove('hidden');m.dataset.backdrop=allowBackdrop?'1':'0'}
function closeModal(){const m=$('#modal');m.classList.add('hidden');$('#modal-actions').innerHTML=''}
function showAbout(){showModal('About Atom Shooter',`<p>This is a clean-room browser/desktop recreation of the 2013 arcade concept: pilot a nano ship, strip electrons from each element, survive the nucleus explosion, and use collected particles to upgrade your loadout.</p><p>All code, vector-style graphics and synthesized audio in this repository are newly created. Original game names and historical references belong to their respective rights holders.</p><p><b>118 elements • Classic • Marathon • Tutorial • Shop • Touch + keyboard/mouse controls</b></p>`,[{label:'Close',primary:true,fn:closeModal}])}
function syncSettings(){const s=save.settings;$('#setting-sfx').checked=s.sfx;$('#setting-music').checked=s.music;$('#setting-side').value=s.side;$('#setting-stick').value=s.stick;$('#setting-deadzone').value=s.deadzone}
function saveSettings(){save.settings={sfx:$('#setting-sfx').checked,music:$('#setting-music').checked,side:$('#setting-side').value,stick:$('#setting-stick').value,deadzone:Number($('#setting-deadzone').value)};audio.configure(save.settings);if(save.settings.music){audio.unlock();audio.startMusic()}persist();applyControlSettings()}
function applyControlSettings(){const tc=$('#touch-controls');tc.classList.toggle('controls-left',save.settings.side==='left');tc.classList.remove('stick-small','stick-medium','stick-large');tc.classList.add(`stick-${save.settings.stick}`)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add('hidden'),1800)}
function formatTime(s){const m=Math.floor(s/60),ss=Math.floor(s%60);return `${m}:${String(ss).padStart(2,'0')}`}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{audio.unlock();const a=b.dataset.action;if(a==='classic')showScreen('table');if(a==='marathon')startGame(0,'marathon');if(a==='tutorial')startGame(0,'tutorial',true);if(a==='shop')showScreen('shop');if(a==='options')showScreen('options');if(a==='about')showAbout();if(a==='home')showScreen('main');if(a==='shop-back')showScreen('main');if(a==='reset-tutorial'){save.tutorialDone=false;persist();toast('Tutorial reset')}if(a==='reset-save')showModal('Reset all progress?',`<p>This deletes unlocked elements, high scores, currency and purchases on this device.</p>`,[{label:'Cancel',fn:closeModal},{label:'Reset',primary:true,fn:()=>{save=structuredClone(DEFAULT_SAVE);persist();audio.configure(save.settings);closeModal();syncSettings();toast('Progress reset')}}])}));
$$('#shop-tabs button').forEach(b=>b.addEventListener('click',()=>{shopTab=b.dataset.tab;renderShop()}));
for(const id of ['setting-sfx','setting-music','setting-side','setting-stick','setting-deadzone'])$('#'+id).addEventListener('input',saveSettings);
$('#pause-btn').addEventListener('click',showPause);
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')&&$('#modal').dataset.backdrop==='1')closeModal()});
const joy=$('#joystick'),knob=$('#joystick-knob');let joyPointer=null;function joyMove(e){if(e.pointerId!==joyPointer)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.34,d=Math.hypot(dx,dy),m=Math.min(1,d/max),nx=d?dx/d:0,ny=d?dy/d:0;knob.style.transform=`translate(${nx*max*m}px,${ny*max*m}px)`;game.setJoystick(nx,ny,m)}joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);audio.unlock();joyMove(e)});joy.addEventListener('pointermove',joyMove);joy.addEventListener('pointerup',e=>{if(e.pointerId===joyPointer){joyPointer=null;knob.style.transform='translate(0,0)';game.setJoystick(0,0,0)}});joy.addEventListener('pointercancel',()=>{joyPointer=null;knob.style.transform='translate(0,0)';game.setJoystick(0,0,0)});
const fire=$('#fire-control');fire.addEventListener('pointerdown',e=>{fire.setPointerCapture(e.pointerId);game.setFire(true)});fire.addEventListener('pointerup',()=>game.setFire(false));fire.addEventListener('pointercancel',()=>game.setFire(false));
window.addEventListener('beforeunload',persist);applyControlSettings();showScreen('main');
