import {ELEMENTS,SHIPS,WEAPONS,ENGINES,MODULES,getElectronShellCounts,findById} from './data.js';
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y},rnd=(a,b)=>a+Math.random()*(b-a);
export class AtomGame{
  constructor(canvas,audio,hooks={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.audio=audio;this.hooks=hooks;this.running=false;this.paused=false;this.last=0;this.keys=new Set();this.joy={x:0,y:0,mag:0};this.fireHeld=false;this.pointerAim=null;this.raf=0;this.bindDesktop()}
  bindDesktop(){window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.code==='Escape'&&this.running)this.hooks.onPause?.()},{passive:false});window.addEventListener('keyup',e=>this.keys.delete(e.code));this.canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){const r=this.canvas.getBoundingClientRect();this.pointerAim={x:(e.clientX-r.left)*1000/r.width,y:(e.clientY-r.top)*1000/r.height}}});this.canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button===0){this.fireHeld=true;this.audio.unlock()}});window.addEventListener('pointerup',e=>{if(e.pointerType==='mouse'&&e.button===0)this.fireHeld=false})}
  getLoadout(save){const ship=findById(SHIPS,save.selectedShip),weapon=findById(WEAPONS,save.selectedWeapon),engine=findById(ENGINES,save.selectedEngine);const mods=(save.selectedModules||[]).map(id=>findById(MODULES,id)).filter(Boolean);const stat={pickup:ship.pickup,gravity:ship.gravity,rate:1,bulletSpeed:1,shipSize:ship.size,electronSpeed:1,time:1};for(const m of mods){if(m.effect==='pickup')stat.pickup*=m.value;if(m.effect==='gravity')stat.gravity*=m.value;if(m.effect==='rate')stat.rate*=m.value;if(m.effect==='bulletSpeed')stat.bulletSpeed*=m.value;if(m.effect==='shipSize')stat.shipSize*=m.value;if(m.effect==='electronSpeed')stat.electronSpeed*=m.value;if(m.effect==='time')stat.time*=m.value}return{ship,weapon,engine,stat}}
  start({elementIndex=0,mode='classic',save,tutorial=false,marathonScore=0}){this.mode=mode;this.save=save;this.tutorial=tutorial;this.elementIndex=clamp(elementIndex,0,ELEMENTS.length-1);this.element=ELEMENTS[this.elementIndex];this.loadout=this.getLoadout(save);this.score=marathonScore||0;this.levelScore=0;this.lives=3;this.elapsed=0;this.phase='electrons';this.explosionTimer=0;this.neutronCollected=0;this.neutronGoal=Math.max(1,Math.ceil(this.element.z/12));this.bullets=[];this.nuclear=[];this.particles=[];this.shake=0;this.messageTimer=0;this.initShip();this.initElectrons();this.running=true;this.paused=false;this.last=performance.now();cancelAnimationFrame(this.raf);this.raf=requestAnimationFrame(t=>this.loop(t));this.emitHUD()}
  initShip(){const {ship,engine,stat}=this.loadout;this.ship={x:500,y:115,vx:0,vy:0,angle:Math.PI/2,r:13*stat.shipSize,mass:ship.mass,thrust:245*ship.thrust*engine.thrust,max:360*engine.max,invuln:1.1,cooldown:0}}
  initElectrons(){this.electrons=[];const counts=getElectronShellCounts(this.element.z),speedScale=this.loadout.stat.electronSpeed;for(let s=0;s<counts.length;s++){const count=counts[s];if(!count)continue;const radius=86+s*43;for(let i=0;i<count;i++){this.electrons.push({shell:s+1,radius,angle:TAU*i/count+rnd(-.06,.06),speed:(.16+.028*(7-s))*speedScale*(i%2?1:-1),state:'orbit',x:0,y:0,vx:0,vy:0,ttl:0,hp:1})}}this.updateElectronPositions(0)}
  setJoystick(x,y,mag){this.joy={x,y,mag}}
  setFire(v){this.fireHeld=v;if(v)this.audio.unlock()}
  setPaused(v){this.paused=v;if(!v){this.last=performance.now();this.raf=requestAnimationFrame(t=>this.loop(t))}}
  stop(){this.running=false;cancelAnimationFrame(this.raf)}
  loop(t){if(!this.running||this.paused)return;let dt=Math.min(.033,(t-this.last)/1000||.016);this.last=t;this.update(dt);this.draw();this.raf=requestAnimationFrame(x=>this.loop(x))}
  input(dt){const s=this.ship;let aim=null,thrust=0;if(this.joy.mag>.08){aim=Math.atan2(this.joy.y,this.joy.x);thrust=this.joy.mag>Number(this.save.settings.deadzone||.38)?this.joy.mag:0}else{let turn=0;if(this.keys.has('ArrowLeft')||this.keys.has('KeyA'))turn-=1;if(this.keys.has('ArrowRight')||this.keys.has('KeyD'))turn+=1;s.angle+=turn*2.65*dt;if(this.keys.has('ArrowUp')||this.keys.has('KeyW'))thrust=1;if(this.keys.has('ArrowDown')||this.keys.has('KeyS'))thrust=-.38;if(this.pointerAim){const dx=this.pointerAim.x-s.x,dy=this.pointerAim.y-s.y;if(this.fireHeld&&!turn)aim=Math.atan2(dy,dx)}}if(aim!==null){let d=((aim-s.angle+Math.PI*3)%TAU)-Math.PI;s.angle+=clamp(d,-3.4*dt,3.4*dt)}if(thrust){s.vx+=Math.cos(s.angle)*s.thrust*thrust/s.mass*dt;s.vy+=Math.sin(s.angle)*s.thrust*thrust/s.mass*dt;this.spawnThruster()}const sp=Math.hypot(s.vx,s.vy);if(sp>s.max){s.vx*=s.max/sp;s.vy*=s.max/sp}if(this.fireHeld||this.keys.has('Space'))this.fire()}
  fire(){const s=this.ship,w=this.loadout.weapon,rate=w.rate*this.loadout.stat.rate;if(s.cooldown>0)return;s.cooldown=1/rate;for(let i=0;i<w.bullets;i++){const center=(w.bullets-1)/2,ang=s.angle+(i-center)*w.spread;const sp=w.speed*this.loadout.stat.bulletSpeed;this.bullets.push({x:s.x+Math.cos(ang)*s.r*1.4,y:s.y+Math.sin(ang)*s.r*1.4,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,ttl:w.life,r:w.size,damage:w.damage})}this.audio.shoot()}
  update(dt){this.elapsed+=dt;this.input(dt);const s=this.ship;s.cooldown=Math.max(0,s.cooldown-dt);s.invuln=Math.max(0,s.invuln-dt);this.updatePhysics(dt);this.updateElectronPositions(dt);this.updateBullets(dt);this.updateNuclear(dt);this.updateParticles(dt);if(this.phase==='electrons'&&this.electrons.every(e=>e.state!=='orbit')){this.phase='unstable';this.explosionTimer=1.25;this.hooks.onObjective?.('The nucleus is unstable…')}if(this.phase==='unstable'){this.explosionTimer-=dt;if(this.explosionTimer<=0)this.explodeNucleus()}if(this.messageTimer>0)this.messageTimer-=dt;this.shake=Math.max(0,this.shake-dt*22);this.emitHUD()}
  updatePhysics(dt){const s=this.ship,dx=500-s.x,dy=500-s.y,d=Math.max(50,Math.hypot(dx,dy));if(this.element.z>=4&&this.phase!=='post'){const base=(18+this.element.z*.72)*this.loadout.stat.gravity;const accel=base*Math.pow(260/d,1.15);s.vx+=dx/d*accel*dt;s.vy+=dy/d*accel*dt}const drag=Math.pow(.992,dt*60);s.vx*=drag;s.vy*=drag;s.x+=s.vx*dt;s.y+=s.vy*dt;const bd=Math.hypot(s.x-500,s.y-500),limit=420-s.r;if(bd>limit){const nx=(s.x-500)/bd,ny=(s.y-500)/bd;s.x=500+nx*limit;s.y=500+ny*limit;const vn=s.vx*nx+s.vy*ny;if(vn>0){s.vx-=1.55*vn*nx;s.vy-=1.55*vn*ny}}const nucleusR=28+Math.sqrt(this.element.z)*2.4;if(this.phase!=='post'&&d<nucleusR+s.r)this.damageShip('nucleus')}
  updateElectronPositions(dt){const s=this.ship;for(const e of this.electrons){if(e.state==='orbit'){e.angle+=e.speed*dt;e.x=500+Math.cos(e.angle)*e.radius;e.y=500+Math.sin(e.angle)*e.radius}else if(e.state==='loose'){e.ttl-=dt;e.x+=e.vx*dt;e.y+=e.vy*dt;const d=Math.hypot(e.x-500,e.y-500);if(d>430||e.ttl<=0)e.state='gone';const pickup=22*this.loadout.stat.pickup+s.r;if(e.state==='loose'&&dist2(e,s)<pickup*pickup){e.state='collected';this.save.electrons++;this.addScore(100);this.audio.collect();this.hooks.onCurrency?.()}}}}
  updateBullets(dt){for(const b of this.bullets){b.ttl-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.ttl<=0)continue;for(const e of this.electrons){if(e.state!=='orbit')continue;const rr=b.r+10;if(dist2(b,e)<rr*rr){e.hp-=b.damage;b.ttl=0;this.audio.hit();this.spark(e.x,e.y,'electron');if(e.hp<=0){e.state='loose';const a=e.angle;e.vx=Math.cos(a)*rnd(55,100);e.vy=Math.sin(a)*rnd(55,100);e.ttl=8;this.addScore(40)}break}}}this.bullets=this.bullets.filter(b=>b.ttl>0&&b.x>-30&&b.y>-30&&b.x<1030&&b.y<1030)}
  explodeNucleus(){this.phase='post';this.audio.explode();this.shake=12;const count=clamp(Math.round(Math.sqrt(this.element.z)*2.2),4,28),needed=this.neutronGoal;let neutrons=0;for(let i=0;i<count;i++){const isN=(i%2===0)||neutrons<needed&&i>=count-needed;if(isN)neutrons++;const a=rnd(0,TAU),sp=rnd(55,150)+this.element.z*.35;this.nuclear.push({x:500+rnd(-8,8),y:500+rnd(-8,8),vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r:isN?11:12,type:isN?'neutron':'proton',ttl:16})}this.hooks.onObjective?.(`Collect ${this.neutronGoal} neutron${this.neutronGoal===1?'':'s'} — avoid protons!`)}
  updateNuclear(dt){const s=this.ship,time=this.loadout.stat.time;for(const p of this.nuclear){if(p.dead)continue;p.ttl-=dt;p.x+=p.vx*dt*time;p.y+=p.vy*dt*time;const d=Math.hypot(p.x-500,p.y-500);if(d>430-p.r){const nx=(p.x-500)/d,ny=(p.y-500)/d,vn=p.vx*nx+p.vy*ny;p.x=500+nx*(430-p.r);p.y=500+ny*(430-p.r);p.vx-=1.7*vn*nx;p.vy-=1.7*vn*ny}const pickup=(p.type==='neutron'?22*this.loadout.stat.pickup:0)+s.r+p.r;if(dist2(p,s)<pickup*pickup){p.dead=true;if(p.type==='neutron'){this.neutronCollected++;this.save.neutrons++;this.addScore(250);this.audio.collect();this.hooks.onCurrency?.();if(this.neutronCollected>=this.neutronGoal){this.completeLevel();return}}else{this.audio.proton();this.damageShip('proton')}}}this.nuclear=this.nuclear.filter(p=>!p.dead&&p.ttl>0)}
  damageShip(reason){const s=this.ship;if(s.invuln>0||!this.running)return;this.lives--;this.audio.proton();this.shake=8;this.burst(s.x,s.y);if(this.lives<=0){this.running=false;cancelAnimationFrame(this.raf);this.hooks.onGameOver?.({score:this.score,reason,element:this.element});return}this.initShip();this.hooks.onLifeLost?.(this.lives)}
  completeLevel(){if(!this.running)return;this.running=false;cancelAnimationFrame(this.raf);this.audio.complete();const timeBonus=Math.max(0,Math.round(2500-this.elapsed*20)),lifeBonus=this.lives*500;this.addScore(timeBonus+lifeBonus);const stars=this.lives===3&&this.elapsed<90?3:this.lives>=2?2:1;this.hooks.onComplete?.({element:this.element,score:this.score,levelScore:this.levelScore,stars,lives:this.lives,time:this.elapsed,mode:this.mode})}
  addScore(n){this.score+=Math.round(n);this.levelScore+=Math.round(n)}
  updateParticles(dt){for(const p of this.particles){p.ttl-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy*=.98}this.particles=this.particles.filter(p=>p.ttl>0)}
  spark(x,y,type){for(let i=0;i<7;i++){const a=rnd(0,TAU),sp=rnd(40,130);this.particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,ttl:rnd(.18,.45),type})}}
  burst(x,y){for(let i=0;i<22;i++){const a=rnd(0,TAU),sp=rnd(80,220);this.particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,ttl:rnd(.35,.8),type:'ship'})}}
  spawnThruster(){if(Math.random()>.55)return;const s=this.ship,a=s.angle+Math.PI;this.particles.push({x:s.x+Math.cos(a)*s.r,y:s.y+Math.sin(a)*s.r,vx:Math.cos(a)*rnd(45,100)-s.vx*.1,vy:Math.sin(a)*rnd(45,100)-s.vy*.1,ttl:rnd(.15,.3),type:'thrust'})}
  emitHUD(){this.hooks.onHUD?.({lives:this.lives,score:this.score,element:this.element,phase:this.phase,orbiting:this.electrons.filter(e=>e.state==='orbit').length,total:this.electrons.length,neutronCollected:this.neutronCollected,neutronGoal:this.neutronGoal})}
  draw(){const c=this.ctx;c.save();c.clearRect(0,0,1000,1000);const sh=this.shake?rnd(-this.shake,this.shake):0;c.translate(sh,sh);this.drawBackground(c);this.drawAtom(c);this.drawParticles(c);this.drawBullets(c);this.drawShip(c);c.restore()}
  drawBackground(c){c.fillStyle='#eef3f5';c.fillRect(-20,-20,1040,1040);c.strokeStyle='rgba(124,151,160,.11)';c.lineWidth=1;for(let i=0;i<24;i++){const x=(i*137)%1000,y=(i*233)%1000;c.beginPath();c.arc(x,y,2,0,TAU);c.fillStyle='rgba(96,155,164,.2)';c.fill();const x2=((i+3)*197)%1000,y2=((i+7)*89)%1000;c.beginPath();c.moveTo(x,y);c.lineTo(x2,y2);c.stroke()}c.beginPath();c.arc(500,500,430,0,TAU);c.lineWidth=3;c.strokeStyle='rgba(84,107,114,.22)';c.stroke()}
  drawAtom(c){for(const r of [...new Set(this.electrons.filter(e=>e.state==='orbit').map(e=>e.radius))]){c.beginPath();c.arc(500,500,r,0,TAU);c.strokeStyle='rgba(96,112,118,.16)';c.lineWidth=14;c.stroke()}for(const e of this.electrons){if(e.state==='gone'||e.state==='collected')continue;c.save();c.translate(e.x,e.y);c.rotate(e.angle+Math.PI/2);c.fillStyle=e.state==='orbit'?'#19aab3':'rgba(25,170,179,.9)';c.shadowBlur=e.state==='loose'?15:7;c.shadowColor='#26b8c0';c.beginPath();c.roundRect(-7,-15,14,30,7);c.fill();c.restore()}if(this.phase!=='post'){const r=28+Math.sqrt(this.element.z)*2.4;const blobs=clamp(Math.round(Math.sqrt(this.element.z)*2),4,20);for(let i=0;i<blobs;i++){const a=i*2.399,rr=(i%4)/4*r*.55,x=500+Math.cos(a)*rr,y=500+Math.sin(a)*rr;c.beginPath();c.arc(x,y,clamp(r*.28,9,16),0,TAU);c.fillStyle=i%2?'#ef355d':'#2aa8d8';c.fill()}c.beginPath();c.arc(500,500,r+5,0,TAU);c.strokeStyle='rgba(255,255,255,.7)';c.lineWidth=3;c.stroke()}for(const p of this.nuclear){c.beginPath();c.arc(p.x,p.y,p.r,0,TAU);c.fillStyle=p.type==='neutron'?'#2aa8d8':'#ef355d';c.shadowBlur=9;c.shadowColor=c.fillStyle;c.fill();c.shadowBlur=0}}
  drawBullets(c){c.fillStyle='#f3b637';for(const b of this.bullets){c.beginPath();c.arc(b.x,b.y,b.r,0,TAU);c.fill()}}
  drawShip(c){const s=this.ship;if(s.invuln>0&&Math.floor(s.invuln*12)%2===0)return;c.save();c.translate(s.x,s.y);c.rotate(s.angle+Math.PI/2);const r=s.r;c.beginPath();c.moveTo(0,-r*1.45);c.lineTo(r*.9,r*1.05);c.lineTo(0,r*.55);c.lineTo(-r*.9,r*1.05);c.closePath();c.fillStyle='#f9fcfd';c.strokeStyle='#2e9ea7';c.lineWidth=4;c.fill();c.stroke();c.beginPath();c.moveTo(0,-r*.75);c.lineTo(r*.32,r*.35);c.lineTo(-r*.32,r*.35);c.closePath();c.fillStyle='#ef355d';c.fill();c.restore()}
  drawParticles(c){for(const p of this.particles){c.globalAlpha=clamp(p.ttl*2,0,1);c.fillStyle=p.type==='electron'?'#18aeb5':p.type==='ship'?'#ef355d':'#f4b23e';c.beginPath();c.arc(p.x,p.y,p.type==='ship'?4:2.5,0,TAU);c.fill()}c.globalAlpha=1}
}
